таблица peas:
| Название атрибута | Тип атрибута | Смысловое значение |
|--------------------|--------------|---------------------|
| st_id             | int          | ID ученика          |
| timest            | timestamp    | Время решения карточки |
| correct           | bool         | Правильно ли решена горошина? |
| subject           | text         | Дисциплина, в которой находится горошина |

таблица studs:
| Название атрибута | Тип атрибута | Смысловое значение                      |
|--------------------|--------------|-----------------------------------------|
| st_id             | int          | ID ученика                              |
| test_grp          | text         | Метка ученика в данном эксперименте     |

таблица final_project_check:
| Название атрибута | Тип атрибута | Смысловое значение                       |
|--------------------|--------------|------------------------------------------|
| st_id             | int          | ID ученика                               |
| sale_time         | timestamp    | Время покупки                            |
| money             | int          | Цена, по которой приобрели данный курс   |
| subject           | text         | Дисциплина                               |

Необходимо в одном запросе выгрузить следующую информацию о группах пользователей:</br>
<ul style="font-size: 15px; line-height: 1.5;">
  <li>ARPU</li>
  <li>ARPAU</li>
  <li>CR в покупку</li>
  <li>СR активного пользователя в покупку</li>
  <li>CR пользователя из активности по математике (subject = ’math’) в покупку курса по математике</li>
</ul>
Активным считается пользователь, за все время решивший больше 10 задач правильно в любых дисциплинах.</br>
Активным по математике считается пользователь, за все время решивший 2 или больше задач правильно по математике.

```sql
WITH activity AS (
                    SELECT p.st_id,
                           COUNT(*) FILTER (WHERE p.correct = TRUE) AS total_correct,
                           COUNT(*) FILTER (WHERE p.correct = TRUE AND p.subject = 'Math') AS math_correct
                      FROM peas p
                     GROUP BY p.st_id),
                     
active_users AS (
                    SELECT st_id,
                           CASE WHEN total_correct > 10 THEN TRUE ELSE FALSE END AS is_active,
                           CASE WHEN math_correct >= 2 THEN TRUE ELSE FALSE END AS is_active_math
                      FROM activity),
                      
merged_data AS (
                    SELECT s.test_grp,
                           au.is_active,
                           au.is_active_math,
                           COALESCE(fp.money, 0) AS money
                      FROM studs s
                      LEFT JOIN active_users au 
                        ON s.st_id = au.st_id
                      LEFT JOIN final_project_check fp 
                        ON s.st_id = fp.st_id),
                        
metrics AS (
                    SELECT test_grp,
                           AVG(money) AS ARPU,
                           SUM(CASE WHEN is_active THEN 1 ELSE 0 END) AS active_users,
                           COUNT(*) AS total_users,
                           SUM(money) AS total_revenue,
                           SUM(CASE WHEN is_active_math THEN 1 ELSE 0 END) AS active_users_math
                      FROM merged_data
                     GROUP BY test_grp)

SELECT
    test_grp,
    ARPU,
    total_revenue::float / active_users AS ARPAU,
    total_revenue::float / total_users AS CR,
    total_revenue::float / active_users AS CR_active,
    total_revenue::float / active_users_math AS CR_math_active
FROM
    metrics;